
#ifndef MOJO_OBJECTS_TYPEDEFS
#define MOJO_OBJECTS_TYPEDEFS

#include <mojo/core/macros.hpp>

#include "forward.hpp"

namespace mojo {

MOJO_DEFINE_POINTER_TYPEDEFS(AudioClip)
MOJO_DEFINE_POINTER_TYPEDEFS(AudioEvent)
MOJO_DEFINE_POINTER_TYPEDEFS(AudioRegion)
MOJO_DEFINE_POINTER_TYPEDEFS(AudioSequence)
MOJO_DEFINE_POINTER_TYPEDEFS(AudioTrack)
MOJO_DEFINE_POINTER_TYPEDEFS(MidiTrack)
MOJO_DEFINE_POINTER_TYPEDEFS(Object)
MOJO_DEFINE_POINTER_TYPEDEFS(Project)
MOJO_DEFINE_POINTER_TYPEDEFS(Track)

} // namespace mojo

#endif
