#! /usr/bin/env python
# encoding: utf-8
# Tim Mayberry, 2008

subdirs = '''
dummy
xml
'''


def init():
    pass


def configure(conf):
    print ("configure mojo-archive")


def build(bld):

    if bld.env['ENABLE_SHARED']:
        bld.shlib(includes='.',
                  export_includes='.',
                  source=bld.path.ant_glob('*.cpp'),
                  uselib=[
                      'GMODULE-2.0',
                      'BOOST_FILESYSTEM',
                      'BOOST_SYSTEM'],
                  use=['GLEAM_SHARED', 'MOJO_CORE_SHARED'],
                  target='mojo-archive',
                  name='MOJO_ARCHIVE_SHARED')

    if bld.env['ENABLE_STATIC']:
        bld.stlib(includes='.',
                  export_includes='.',
                  source=bld.path.ant_glob('*.cpp'),
                  uselib=[
                      'GMODULE-2.0',
                      'BOOST_FILESYSTEM',
                      'BOOST_SYSTEM'],
                  use=['GLEAM_STATIC', 'MOJO_CORE_STATIC'],
                  target='mojo-archive',
                  name='MOJO_ARCHIVE_STATIC')

    bld.recurse(subdirs)
