#! /usr/bin/env python
# encoding: utf-8
# Tim Mayberry, 2008

subdirs = '''
dummy
xml
'''


def init():
    pass


def configure(conf):
    print ("configure mojo-archive")


def build(bld):

    if bld.env.ENABLE_AMALGAMATION:
        source = 'mojo-archive.cpp'
        defines = 'MOJO_AMALGAMATED'
    else:
        source = bld.path.ant_glob('*.cpp',
                    excl='mojo-archive.cpp')
        defines = ''

    uselib = ['GMODULE-2.0', 'BOOST_FILESYSTEM', 'BOOST_SYSTEM']
    target = 'mojo-archive'

    if bld.env['ENABLE_SHARED']:
        bld.shlib(includes='.',
                  export_includes='.',
                  source=source,
                  uselib=uselib,
                  use=['MOJO_CORE_SHARED'],
                  target=target,
                  name='MOJO_ARCHIVE_SHARED')

    if bld.env['ENABLE_STATIC']:
        bld.stlib(includes='.',
                  export_includes='.',
                  source=source,
                  uselib=uselib,
                  use=['MOJO_CORE_STATIC'],
                  target=target,
                  name='MOJO_ARCHIVE_STATIC')

    bld.recurse(subdirs)
