# vim: tabstop=4 expandtab shiftwidth=4

import tools.pkgconfig as pkgconfig

Import ('env')

gleam_deps = \
{
    'glib-2.0'      : '2.10.1',
    'gthread-2.0'   : '2.10.1',
    'glibmm-2.4'    : '2.8.1'
}

gleam_env = env.Clone()

pkgconfig.ParseDependencies ( gleam_env, gleam_deps )

gleam_source_files = Split("""
blink_timer.cpp
dispatcher.cpp
filesystem_paths.cpp
manual_dispatcher.cpp
semaphore.cpp
standard_timer.cpp
terminate_process.cpp
timer.cpp
utils.cpp
""")

gleam_posix_source_files = Split("""
posix_signals.cpp
""")

if env['PLATFORM'] == 'posix':
	gleam_source_files += gleam_posix_source_files

libgleam = gleam_env.SharedLibrary ( 'gleam', gleam_source_files )

Default (libgleam)

if env['BUILD_TESTS']:
        SConscript  ( 'tests/SConscript' )

