#! /usr/bin/env python
# encoding: utf-8
# Tim Mayberry, 2008

posix_files='''
posix_signals.cpp
'''.split()

def init():
	pass

def configure(conf):
	pass

def build(bld):
	obj = bld.new_task_gen('cxx', 'shlib')
	exclude_files=posix_files
	obj.find_sources_in_dirs('.', excludes=exclude_files)
	obj.includes ='. ..'
	obj.uselib ='GLIBMM-2.4'
	obj.target = 'gleam'
	obj.name = 'GLEAM'

        if bld.env['BUILD_TESTS']:
                bld.add_subdirs('tests')
