#! /usr/bin/env python
# encoding: utf-8
# Tim Mayberry, 2008

posix_files = '''
posix_signals.cpp
'''.split()


def init():
    pass


def configure(conf):
    pass


def build(bld):

    if bld.env.ENABLE_SHARED:
        bld.shlib(
            includes='. ..',
            export_includes='..',  # this should probably be .
            source=bld.path.ant_glob('*.cpp', excl=posix_files),
            uselib=['GLIBMM-2.4'],
            target='gleam',
            name='GLEAM_SHARED')

    if bld.env['BUILD_TESTS']:
        bld.recurse('tests')
