#! /usr/bin/env python
# encoding: utf-8
# Tim Mayberry, 2008

posix_files='''
posix_signals.cpp
'''.split()

def init():
	pass

def configure(conf):
	pass

def build(bld):
	gleam_lib = bld(
		features = [ 'cxx', 'cshlib' ],
		includes = '. ..',
		export_incdirs = '..', # this should probably be .
		uselib = ['GLIBMM-2.4'],
		target = 'gleam',
		name = 'GLEAM')

	exclude_files=posix_files
	gleam_lib.find_sources_in_dirs('.', excludes=exclude_files)

        if bld.env['BUILD_TESTS']:
                bld.add_subdirs('tests')
