#! /usr/bin/env python
# encoding: utf-8
# Tim Mayberry, 2008


def init():
    pass


def configure(conf):
    print "configure mojo-audio-driver-portaudio"
    conf.check_cfg(
        package='portaudio-2.0',
        atleast_version='19',
        args='--cflags --libs',
        mandatory=1)


def build(bld):

    if bld.env['ENABLE_SHARED']:
        bld.shlib(includes='.',
                  source=bld.path.ant_glob('*.cpp'),
                  uselib=[
                      'GMODULE-2.0',
                      'BOOST_FILESYSTEM',
                      'BOOST_SYSTEM'],
                  use=[
                      'GLEAM',
                      'MOJO_AUDIO_DRIVER_SHARED',
                      'MOJO_CORE_SHARED'],
                  target='mojo-audio-driver-portaudio',
                  name='MOJO_AUDIO_DRIVER_PORTAUDIO')

    if bld.env['ENABLE_STATIC']:
        bld.stlib(includes='.',
                  source=bld.path.ant_glob('*.cpp'),
                  uselib=[
                      'GMODULE-2.0',
                      'BOOST_FILESYSTEM',
                      'BOOST_SYSTEM'],
                  use=[
                      'GLEAM',
                      'MOJO_AUDIO_DRIVER_STATIC',
                      'MOJO_CORE_STATIC'],
                  target='mojo-audio-driver-portaudio',
                  name='MOJO_AUDIO_DRIVER_PORTAUDIO')
