#! /usr/bin/env python
# encoding: utf-8
# Tim Mayberry, 2008


def init():
    pass


def configure(conf):
    print ("configure mojo-audio-driver-portaudio")
    conf.check_cfg(
        package='portaudio-2.0',
        atleast_version='19',
        args='--cflags --libs',
        mandatory=1)


def build(bld):

    if bld.env.ENABLE_AMALGAMATION:
        source = 'mojo-portaudio-audio-driver.cpp'
        defines = 'MOJO_AMALGAMATED'
    else:
        source = bld.path.ant_glob('*.cpp',
                                   excl='mojo-portaudio-audio-driver.cpp')
        defines = ''

    uselib = [
        'GMODULE-2.0',
        'BOOST_FILESYSTEM',
        'BOOST_SYSTEM',
        'PORTAUDIO-2.0']
    target = 'mojo-audio-driver-portaudio'

    if bld.env.ENABLE_SHARED:
        use_shared = [
            'MOJO_AUDIO_DRIVER_SHARED',
            'MOJO_CORE_SHARED']
        bld.shlib(includes='.',
                  source=source,
                  uselib=uselib,
                  use=use_shared,
                  defines=defines,
                  target=target,
                  name='MOJO_AUDIO_DRIVER_PORTAUDIO_SHARED')

    if bld.env.ENABLE_STATIC:
        use_static = [
            'MOJO_AUDIO_DRIVER_STATIC',
            'MOJO_CORE_STATIC']
        bld.stlib(includes='.',
                  source=source,
                  uselib=uselib,
                  use=use_static,
                  defines=defines,
                  target=target,
                  name='MOJO_AUDIO_DRIVER_PORTAUDIO_STATIC')
