#! /usr/bin/env python
# encoding: utf-8
# Tim Mayberry, 2008


def init():
    pass


def configure(conf):
    print "configure LADSPAAudioEffect"


def build(ctx):
    shlib = ctx(
        features="cxx cxxshlib",
        includes='.',
        source=ctx.path.ant_glob('*.cpp'),
        uselib=['LADSPA'],
        use='MOJO',
        target='ladspa_audio_effect',
        name='LADSPA_AUDIO_EFFECT')
