#! /usr/bin/env python
# encoding: utf-8
# Tim Mayberry, 2008


def init():
    pass


def configure(conf):
    print ("configure mojo-audio-effect-ladspa")


def build(bld):

    if bld.env.ENABLE_AMALGAMATION:
        source = 'mojo-ladspa-audio-effect.cpp'
        defines = 'MOJO_AMALGAMATED'
    else:
        source = bld.path.ant_glob('*.cpp',
                                   excl='mojo-ladspa-audio-effect.cpp')
        defines = ''

    uselib = ['GMODULE-2.0', 'BOOST_FILESYSTEM', 'BOOST_SYSTEM']
    target = 'mojo-ladspa-audio-effect'

    if bld.env['ENABLE_SHARED']:
        bld.shlib(includes='.',
                  source=source,
                  uselib=uselib,
                  use=[
                      'MOJO_AUDIO_EFFECT_SHARED',
                      'MOJO_CORE_SHARED'],
                  defines=defines,
                  target='mojo-audio-effect-ladspa',
                  name='MOJO_AUDIO_EFFECT_LADSPA')

    if bld.env['ENABLE_STATIC']:
        bld.stlib(includes='.',
                  source=source,
                  uselib=uselib,
                  use=[
                      'MOJO_AUDIO_EFFECT_STATIC',
                      'MOJO_CORE_STATIC'],
                  defines=defines,
                  target='mojo-audio-effect-ladspa',
                  name='MOJO_AUDIO_EFFECT_LADSPA')
