#! /usr/bin/env python
# encoding: utf-8
# Tim Mayberry, 2008


def init():
    pass


def configure(conf):
    print ("configure mojo-audio-effect-ladspa")


def build(bld):

    source = 'mojo-ladspa-audio-effect.cpp'
    uselib = ['GMODULE-2.0', 'BOOST_FILESYSTEM', 'BOOST_SYSTEM']
    target = 'mojo-ladspa-audio-effect'

    if bld.env['ENABLE_SHARED']:
        bld.shlib(includes='.',
                  source=source,
                  uselib=uselib,
                  use=[
                      'MOJO_AUDIO_EFFECT_SHARED',
                      'MOJO_CORE_SHARED'],
                  target='mojo-audio-effect-ladspa',
                  name='MOJO_AUDIO_EFFECT_LADSPA')

    if bld.env['ENABLE_STATIC']:
        bld.stlib(includes='.',
                  source=source,
                  uselib=uselib,
                  use=[
                      'MOJO_AUDIO_EFFECT_STATIC',
                      'MOJO_CORE_STATIC'],
                  target='mojo-audio-effect-ladspa',
                  name='MOJO_AUDIO_EFFECT_LADSPA')
