# vim: tabstop=4 expandtab shiftwidth=4

import tools.pkgconfig as pkgconfig

Import ('env')

mojo_deps = \
{
#    'glib-2.0'      : '2.10.1',
#    'gthread-2.0'   : '2.10.1',
#    'glibmm-2.4'    : '2.8.1'
}

mojo_env = env.Copy()

mojo_env.Append(LIBS = ['boost_filesystem', 'boost_signals', 'booty'] )

#pkgconfig.ParseDependencies ( mojo_env, mojo_deps )

mojo_source_files = Split("""
application.cpp
audio_track.cpp
directory_names.cpp
filesystem_paths.cpp
project.cpp
project_directory.cpp
type_name_registry.cpp
""")

libmojo = mojo_env.SharedLibrary ( 'mojo', mojo_source_files )

Default (libmojo)
