# vim: tabstop=4 expandtab shiftwidth=4

import tools.pkgconfig as pkgconfig

Import ('env')

mojo_deps = \
{
#    'glib-2.0'      : '2.10.1',
    'gmodule-2.0'   : '2.10.1'
#    'gthread-2.0'   : '2.10.1',
#    'glibmm-2.4'    : '2.8.1'
}

mojo_env = env.Clone()

mojo_env.Append(LIBS = ['boost_filesystem', 'gleam' ] )

pkgconfig.ParseDependencies ( mojo_env, mojo_deps )

mojo_typesystem_files = Split("""
typesystem/type_system.cpp
""")

mojo_utils_files = Split("""
utils/file_utils.cpp
utils/glib_library.cpp
utils/library.cpp
utils/search_path.cpp
utils/resource.cpp
""")

mojo_objects_files = Split("""
objects/audio_clip.cpp
objects/audio_event.cpp
objects/audio_region.cpp
objects/audio_region_event.cpp
objects/audio_sequence.cpp
objects/audio_track.cpp
objects/event.cpp
objects/midi_track.cpp
objects/project.cpp
objects/track.cpp
""")

mojo_app_files = Split("""
app/app.cpp
app/type_names.cpp
app/register_types.cpp
app/module_utils.cpp
""")

mojo_core_files = Split("""
core/archive.cpp
core/archive_module.cpp
core/audio_driver_module.cpp
core/audio_effect.cpp
core/audio_effect_info.cpp
core/audio_effect_module.cpp
core/audio_file.cpp
core/audio_file_format.cpp
core/audio_file_module.cpp
core/module.cpp
""")

mojo_rtg_files = Split("""
rtg/graph.cpp
""")

mojo_source_files = Split("""
directory_names.cpp
filesystem_paths.cpp
project_directory.cpp
sample_block.cpp
""")

mojo_source_files += mojo_typesystem_files
mojo_source_files += mojo_utils_files
mojo_source_files += mojo_objects_files
mojo_source_files += mojo_app_files
mojo_source_files += mojo_rtg_files
mojo_source_files += mojo_core_files

libmojo = mojo_env.SharedLibrary ( 'mojo', mojo_source_files )

Default (libmojo)

if env['BUILD_TESTS']:
        SConscript  ( 'tests/SConscript' )
