# vim: tabstop=4 expandtab shiftwidth=4

import tools.pkgconfig as pkgconfig

Import ('env')

mojo_deps = \
{
#    'glib-2.0'      : '2.10.1',
    'gmodule-2.0'   : '2.10.1'
#    'gthread-2.0'   : '2.10.1',
#    'glibmm-2.4'    : '2.8.1'
}

mojo_env = env.Clone()

mojo_env.Append(LIBS = ['boost_filesystem', 'gleam' ] )

pkgconfig.ParseDependencies ( mojo_env, mojo_deps )

mojo_typesystem_files = Split("""
typesystem/type_system.cpp
""")

mojo_source_files = Split("""
app.cpp
archive.cpp
archive_module.cpp
audio_clip.cpp
audio_driver_module.cpp
audio_effect.cpp
audio_effect_info.cpp
audio_effect_module.cpp
audio_event.cpp
audio_file.cpp
audio_file_format.cpp
audio_file_module.cpp
audio_region.cpp
audio_region_event.cpp
audio_track.cpp
audio_sequence.cpp
directory_names.cpp
event.cpp
filesystem_paths.cpp
file_utils.cpp
glib_library.cpp
graph.cpp
library.cpp
midi_track.cpp
module.cpp
module_utils.cpp
project.cpp
project_directory.cpp
register_types.cpp
resource.cpp
sample_block.cpp
search_path.cpp
track.cpp
type_names.cpp
""")

mojo_source_files += mojo_typesystem_files

libmojo = mojo_env.SharedLibrary ( 'mojo', mojo_source_files )

Default (libmojo)

if env['BUILD_TESTS']:
        SConscript  ( 'tests/SConscript' )
