#! /usr/bin/env python
# encoding: utf-8
# Tim Mayberry, 2008


def init():
    pass


def configure(conf):
    print "configure mojo"


def build(bld):

    if bld.env['ENABLE_AMALGAMATION']:
        if bld.env['ENABLE_SHARED']:
            bld.shlib(includes='.',
                      export_includes='core',
                      source='core/core.cpp',
                      uselib=[
                          'GMODULE-2.0',
                          'BOOST_FILESYSTEM',
                          'BOOST_SYSTEM'],
                      use=['GLEAM'],
                      defines='MOJO_CORE_AMALGAMATED',
                      target='mojo-core',
                      name='MOJO_CORE_SHARED_AMALGAMATED')

            bld.stlib(includes='.',
                      export_includes='core',
                      source='core/core.cpp',
                      uselib=[
                          'GMODULE-2.0',
                          'BOOST_FILESYSTEM',
                          'BOOST_SYSTEM'],
                      use=['GLEAM'],
                      defines='MOJO_CORE_AMALGAMATED',
                      target='mojo-core',
                      name='MOJO_CORE_STATIC_AMALGAMATED')

#    if ctx.env['BUILD_TESTS']:
#        ctx.recurse('tests')
