#! /usr/bin/env python
# encoding: utf-8
# Tim Mayberry, 2008

def init():
	pass

def configure(conf):
	print "configure mojo"

def build(bld):
	mojo_lib = bld(
		features = [ 'cxx', 'cshlib' ],
		includes ='. ..',
		uselib = ['GMODULE-2.0', 'BOOST_FILESYSTEM', 'BOOST_SYSTEM'],
		uselib_local ='GLEAM',
		target = 'mojo',
		name = 'MOJO')

	mojo_lib.find_sources_in_dirs('. project session rtg typesystem utils app core fs')

        if bld.env['BUILD_TESTS']:
                bld.add_subdirs('tests')
