# vim: tabstop=4 expandtab shiftwidth=4

import tools.pkgconfig as pkgconfig

Import ('env')

ark_env = env.Copy()

ark_source_files = Split("""
type_system.cpp
""")

libark = ark_env.SharedLibrary ( 'ark', ark_source_files )

Default (libark)

dummy_archive_env = env.Copy()

#dummy_archive_env.Append(LIBS = ['boost_serialization'] )

dummy_archive_source_files = Split("""
dummy_archive/archive.cpp
""")

libdummy_archive = dummy_archive_env.SharedLibrary ( 'dummy_archive', dummy_archive_source_files )

Default (libdummy_archive)

if env['BUILD_TESTS']:
        SConscript  ( 'tests/SConscript' )
