
#ifndef MOJO_CORE_TYPEDEFS
#define MOJO_CORE_TYPEDEFS

#include "macros.hpp"
#include "forward.hpp"

namespace mojo {

MOJO_DEFINE_ALL_TYPEDEFS(Archive)
MOJO_DEFINE_ALL_TYPEDEFS(ArchiveModule)
MOJO_DEFINE_ALL_TYPEDEFS(AudioDevice)
MOJO_DEFINE_ALL_TYPEDEFS(AudioDriverModule)
MOJO_DEFINE_ALL_TYPEDEFS(AudioEffect)
MOJO_DEFINE_ALL_TYPEDEFS(AudioEffectInfo)
MOJO_DEFINE_ALL_TYPEDEFS(AudioEffectModule)
MOJO_DEFINE_ALL_TYPEDEFS(AudioEffectParameterInfo)
MOJO_DEFINE_ALL_TYPEDEFS(AudioFile)
MOJO_DEFINE_ALL_TYPEDEFS(AudioFileModule)
MOJO_DEFINE_ALL_TYPEDEFS(AudioFileFormat)
MOJO_DEFINE_ALL_TYPEDEFS(Module)
MOJO_DEFINE_ALL_TYPEDEFS(Object)
MOJO_DEFINE_ALL_TYPEDEFS(StateTracker)

} // namespace mojo

#endif
