#! /usr/bin/env python
# encoding: utf-8
# Tim Mayberry, 2008

windows_sources = '''
native/windows_mmcss.cpp
'''.split()


def init():
    pass


def configure(conf):
    print ("configure mojo-core")


def build(bld):

    defines = ['PROGRAM_DIR_NAME="' + bld.env.PROGRAM_DIR_NAME + '"']
    if bld.env.ENABLE_AMALGAMATION:
        source = 'mojo-core.cpp'
        defines += ['MOJO_CORE_AMALGAMATED']
    else:
        source = bld.path.ant_glob(
            '**/*.cpp',
            excl='mojo-core.cpp')
        if bld.env['target_platform'] == 'windows':
            source += windows_sources

    uselib = ['GLIB-2.0', 'GMODULE-2.0', 'BOOST_FILESYSTEM', 'BOOST_SYSTEM']

    if bld.env.ENABLE_SHARED:
        bld.shlib(includes='.',
                  export_includes='.',
                  source=source,
                  uselib=uselib,
                  use=['src_include_path'],
                  defines=defines,
                  target='mojo-core',
                  name='MOJO_CORE_SHARED')

    if bld.env.ENABLE_STATIC:
        bld.stlib(includes='.',
                  export_includes='.',
                  source=source,
                  uselib=uselib,
                  use=['src_include_path'],
                  defines=defines,
                  target='mojo-core',
                  name='MOJO_CORE_STATIC')
