#! /usr/bin/env python
# encoding: utf-8
# Tim Mayberry, 2008


def init():
    pass


def configure(conf):
    print ("configure mojo-core")


def build(bld):
    uselib = ['GLIB-2.0', 'GMODULE-2.0', 'BOOST_FILESYSTEM', 'BOOST_SYSTEM']
    use_local_static = ['src_include_path', 'CPPFORMAT_STATIC']
    use_local_shared = ['src_include_path', 'CPPFORMAT_SHARED']

    if bld.env.TARGET_PLATFORM == 'windows':
        uselib += ['WINMM']

    defines = ['PROGRAM_DIR_NAME="' + bld.env.PROGRAM_DIR_NAME + '"']
    if bld.env.ENABLE_AMALGAMATION:
        source = 'mojo-core.cpp'
        defines += ['MOJO_AMALGAMATED']
    else:
        source = bld.path.ant_glob(
            '**/*.cpp',
            excl=['mojo-core.cpp', 'native'])
        if bld.env.TARGET_PLATFORM == 'windows':
            source += bld.path.ant_glob(
                'native/windows*.cpp')

    if bld.env.ENABLE_SHARED:
        bld.shlib(includes='.',
                  export_includes='.',
                  source=source,
                  uselib=uselib,
                  use=use_local_shared,
                  defines=defines,
                  target='mojo-core',
                  name='MOJO_CORE_SHARED')

    if bld.env.ENABLE_STATIC:
        bld.stlib(includes='.',
                  export_includes='.',
                  source=source,
                  uselib=uselib,
                  use=use_local_static,
                  defines=defines,
                  target='mojo-core',
                  name='MOJO_CORE_STATIC')
