# vim: tabstop=4 expandtab shiftwidth=4

Import ('env')

booty_env = env.Copy()

booty_env.Append(LIBS = ['boost_filesystem'])

booty_source_files = Split("""
file_utils.cpp
search_path.cpp
""")

libbooty = booty_env.SharedLibrary ( 'booty', booty_source_files )

Default (libbooty)
