# vim: tabstop=4 expandtab shiftwidth=4

import tools.pkgconfig as pkgconfig

Import ('env')

sndfile_deps = { 'sndfile' : '1.0' }

sndfile_env = env.Copy()

pkgconfig.ParseDependencies ( sndfile_env, sndfile_deps )

sndfile_source_files = Split("""
sndfile_audio_file.cpp
sndfile_audio_file_plugin.cpp
sndfile_audio_file_format.cpp
""")

sndfile_audio_file = sndfile_env.SharedLibrary ( 'sndfile_audio_file', sndfile_source_files )

Default (sndfile_audio_file)

SConscript  ( 'dummy_archive/SConscript' )
