#! /usr/bin/env python
# encoding: utf-8
# Tim Mayberry, 2008


def init():
    pass


def configure(conf):
    print ("configure mojo-engine")


def build(bld):

    uselibs = ['GMODULE-2.0', 'BOOST_FILESYSTEM', 'BOOST_SYSTEM']
    use_local_shared = ['GLEAM_SHARED', 'MOJO_CORE_SHARED']
    use_local_static = ['GLEAM_STATIC', 'MOJO_CORE_STATIC']

    if bld.env.ENABLE_AMALGAMATION:
        source = 'mojo-engine.cpp'
        defines = 'MOJO_ENGINE_AMALGAMATED'
    else:
        source = bld.path.ant_glob(
            '**/*.cpp',
            excl='mojo-engine.cpp')
        defines = ''

    if bld.env.ENABLE_SHARED:
        bld.shlib(includes='.',
                  export_includes='.',
                  source=source,
                  uselib=uselibs,
                  use=use_local_shared,
                  defines=defines,
                  target='mojo-engine',
                  name='MOJO_ENGINE_SHARED')

    if bld.env.ENABLE_STATIC:
        bld.stlib(includes='.',
                  export_includes='.',
                  source='mojo-engine.cpp',
                  uselib=uselibs,
                  use=use_local_static,
                  defines=defines,
                  target='mojo-engine',
                  name='MOJO_ENGINE_STATIC')
