#! /usr/bin/env python
# encoding: utf-8
# Tim Mayberry, 2008

uselibs = ['GMODULE-2.0', 'BOOST_FILESYSTEM', 'BOOST_SYSTEM']


def init():
    pass


def configure(conf):
    print "configure mojo-engine"


def build(bld):

    if bld.env['ENABLE_AMALGAMATION']:
        if bld.env['ENABLE_SHARED']:
            bld.shlib(includes='.',
                      export_includes='.',
                      source='mojo-engine.cpp',
                      uselib=uselibs,
                      use=['GLEAM', 'MOJO_CORE_SHARED'],
                      defines='MOJO_ENGINE_AMALGAMATED',
                      target='mojo-engine-a',
                      name='MOJO_ENGINE_SHARED')

        if bld.env['ENABLE_STATIC']:
            bld.stlib(includes='.',
                      export_includes='.',
                      source='mojo-engine.cpp',
                      uselib=uselibs,
                      use=['GLEAM', 'MOJO_CORE_STATIC'],
                      defines='MOJO_ENGINE_AMALGAMATED',
                      target='mojo-engine-a',
                      name='MOJO_ENGINE_STATIC')

    else:

        if bld.env['ENABLE_SHARED']:
            bld.shlib(includes='.',
                      export_includes='.',
                      source=bld.path.ant_glob(
                          '**/*.cpp',
                          excl='mojo-engine.cpp'),
                      uselib=uselibs,
                      use=['GLEAM'],
                      target='mojo-engine',
                      name='MOJO_ENGINE_SHARED')

        if bld.env['ENABLE_STATIC']:
            bld.stlib(includes='.',
                      export_includes='.',
                      source=bld.path.ant_glob(
                          '**/*.cpp',
                          excl='mojo-engine.cpp'),
                      uselib=uselibs,
                      use=['GLEAM'],
                      target='mojo-engine',
                      name='MOJO_ENGINE_STATIC')
