#! /usr/bin/env python
# encoding: utf-8
# Tim Mayberry, 2008

def init():
	pass

def configure(conf):
	print "configure JACKAudioDriver"

def build(bld):
        obj = bld.new_task_gen('cxx', 'shlib')
	obj.find_sources_in_dirs('.')
	obj.includes ='. ../../../'
	obj.uselib = ['JACK']
	obj.uselib_local ='MOJO'
	obj.target = 'jack_audio_driver'
	obj.name = 'JACK_AUDIO_DRIVER'
