#! /usr/bin/env python
# encoding: utf-8
# Tim Mayberry, 2008

def init():
	pass

def configure(conf):
	print "configure JACKAudioDriver"

def build(ctx):
	shlib = ctx(
		features = "cxx cxxshlib",
		includes = '.',
		source = ctx.path.ant_glob('*.cpp'),
		uselib = ['JACK'],
		use ='MOJO',
		target = 'jack_audio_driver',
		name = 'JACK_AUDIO_DRIVER')
