#ifndef MOJO_AUDIO_DRIVER_TYPEDEFS_H
#define MOJO_AUDIO_DRIVER_TYPEDEFS_H

M_DEFINE_ALL_TYPEDEFS(AudioDevice)
M_DEFINE_ALL_TYPEDEFS(AudioDriver)
M_DEFINE_ALL_TYPEDEFS(AudioDriverModule)

#endif // MOJO_AUDIO_DRIVER_TYPEDEFS_H
