#ifndef MOJO_AUDIO_DRIVER_TYPEDEFS_H
#define MOJO_AUDIO_DRIVER_TYPEDEFS_H

namespace mojo {

M_DEFINE_ALL_TYPEDEFS(AudioDevice)
M_DEFINE_ALL_TYPEDEFS(AudioDriver)
M_DEFINE_ALL_TYPEDEFS(AudioDriverModule)

} // namespace mojo

#endif // MOJO_AUDIO_DRIVER_TYPEDEFS_H
