#! /usr/bin/env python
# encoding: utf-8
# Tim Mayberry, 2008

subdirs = '''
portaudio
'''


def init():
    pass


def configure(conf):
    print ("configure mojo-audio-driver")
    conf.recurse(subdirs)


def build(bld):

    uselib=[ 'GMODULE-2.0', 'BOOST_FILESYSTEM', 'BOOST_SYSTEM']
    target='mojo-audio-driver'
    source=bld.path.ant_glob('*.cpp')

    if bld.env.ENABLE_SHARED:
        bld.shlib(includes='.',
                  export_includes='.',
                  source=source,
                  uselib=uselib,
                  use=['MOJO_CORE_SHARED'],
                  target=target,
                  name='MOJO_AUDIO_DRIVER_SHARED')

    if bld.env.ENABLE_STATIC:
        bld.stlib(includes='.',
                  export_includes='.',
                  source=source,
                  uselib=uselib,
                  use=['MOJO_CORE_STATIC'],
                  target=target,
                  name='MOJO_AUDIO_DRIVER_STATIC')

    bld.recurse(subdirs)
