# vim: tabstop=4 expandtab shiftwidth=4

import tools.pkgconfig as pkgconfig

Import ('env')

gmojo_deps = \
{
    'gtk+-2.0'             : '2.8.1',
    'goocanvas'            : '0.6',
}

gmojo_env = env.Copy()

gmojo_env.Append(LIBS = ['boost_signals', 'mojo', 'gleam' ])

pkgconfig.ParseDependencies ( gmojo_env, gmojo_deps )

gtk_source_files = Split("""
gtk/window.cpp
""")

actions_source_files = Split("""
actions/app_action_group.cpp
actions/app_actions.cpp
actions/project_action_group.cpp
actions/project_actions.cpp
actions/edit_window_menu_action_group.cpp
""")

dialogs_source_files = Split("""
dialogs/audio_file_import_dialog.cpp
dialogs/new_audio_track_dialog.cpp
""")

utils_source_files = Split("""
utils/window_title.cpp
utils/signal_handler.cpp
""")

gmojo_source_files = Split("""
app.cpp
audio_track_control.cpp
audio_track_view_item.cpp
track_canvas.cpp
track_view.cpp
track_view_item.cpp
edit_window.cpp
edit_window_menu_ui_definition.cpp
project.cpp
project_view.cpp
main.cpp
""")

all_source_files = \
gtk_source_files + \
actions_source_files + \
dialogs_source_files + \
utils_source_files + \
gmojo_source_files

gmojo = gmojo_env.Program( env['VERSIONED_NAME'], all_source_files)

Default(gmojo)

env.Install(env['BINDIR'], gmojo)
