# vim: tabstop=4 expandtab shiftwidth=4

import tools.pkgconfig as pkgconfig

Import ('env')

gmojo_deps = \
{
    'gtk+-2.0'             : '2.8.1',
    'goocanvas'            : '0.6',
}

gmojo_env = env.Copy()

gmojo_env.Append(LIBS = ['boost_signals', 'mojo', 'gleam', 'booty', 'ark'])

pkgconfig.ParseDependencies ( gmojo_env, gmojo_deps )

gtk_source_files = Split("""
gtk/window.cpp
""")

goo_source_files = Split("""
goo/canvas.cpp
""")

actions_source_files = Split("""
actions/application_action_group.cpp
actions/application_actions.cpp
actions/project_action_group.cpp
actions/project_actions.cpp
actions/edit_window_menu_action_group.cpp
""")

dialogs_source_files = Split("""
dialogs/audio_file_import_dialog.cpp
dialogs/new_audio_track_dialog.cpp
""")

gmojo_source_files = Split("""
application.cpp
track_view.cpp
edit_window.cpp
edit_window_menu_ui_definition.cpp
project_view.cpp
main.cpp
window_title.cpp
signal_handler.cpp
""")

all_source_files = \
gtk_source_files + \
goo_source_files + \
actions_source_files + \
dialogs_source_files + \
gmojo_source_files

gmojo = gmojo_env.Program( env['VERSIONED_NAME'], all_source_files)

Default(gmojo)

env.Install(env['BINDIR'], gmojo)
