
#ifndef MOJO_PROJECT_TYPEDEFS
#define MOJO_PROJECT_TYPEDEFS

#include "mojo/core/macros.hpp"

#include "forward.hpp"

namespace mojo {

MOJO_DEFINE_ALL_TYPEDEFS(Object)

MOJO_DEFINE_ALL_TYPEDEFS(AudioClip)
MOJO_DEFINE_ALL_TYPEDEFS(AudioEvent)
MOJO_DEFINE_ALL_TYPEDEFS(AudioRegion)
MOJO_DEFINE_ALL_TYPEDEFS(AudioSequence)
MOJO_DEFINE_ALL_TYPEDEFS(AudioTrack)
MOJO_DEFINE_ALL_TYPEDEFS(MidiTrack)
MOJO_DEFINE_ALL_TYPEDEFS(Project)
MOJO_DEFINE_ALL_TYPEDEFS(StateTracker)
MOJO_DEFINE_ALL_TYPEDEFS(Track)

} // namespace mojo

#endif
