# vim: tabstop=4 expandtab shiftwidth=4

import tools.pkgconfig as pkgconfig

Import ('env')

xml_env = env.Clone()

xml_source_files = Split("""
xml_archive.cpp
xml_archive_module.cpp
""")

xml_archive = xml_env.SharedLibrary ( 'xml_archive', xml_source_files )

Default (xml_archive)
