#! /usr/bin/env python
# encoding: utf-8
# Tim Mayberry, 2008

def init():
	pass

def configure(conf):
	print "configure XMLArchive"

def build(ctx):
	shlib = ctx(
		features = "cxx cxxshlib",
		includes = '.',
		source = ctx.path.ant_glob('*.cpp'),
		use ='MOJO',
		target = 'xml_archive',
		name = 'XML_ARCHIVE')
