# -*- python -*-
# vim: tabstop=4 expandtab shiftwidth=4

import tools.pkgconfig as pkgconfig

Import ('env')

ark_test_env = env.Copy()

ark_test_env.Append(CXXFLAGS = '-DBOOST_TEST_DYN_LINK')
ark_test_env.Append(LIBS = [ 'boost_unit_test_framework', 'ark', 'dummy_archive' ])

dummy_archive_test = ark_test_env.Program ( 'test_dummy_archive', 'test_dummy_archive.cpp' )

Default (dummy_archive_test)
