#ifndef MOJO_CORE_COMMON_HEADER_H
#define MOJO_CORE_COMMON_HEADER_H

/**
 * This is the common header file that is included by
 * each header file.
 */

// This is generated by the build system
#include "mojo/core/config/config.hpp"

#include "mojo/core/config/target_platform.hpp"
#include "mojo/core/config/compiler_defines.hpp"
#include "mojo/core/config/visibility.hpp"
#include "mojo/core/config/version.hpp"

/**
 * These are the common system includes required by header files in mojo-core.
 * Not all header files require all these includes but they can rely on them
 * being already included.
 */

#include <atomic>
#include <condition_variable>
#include <chrono>
#include <cinttypes>
#include <cstdint>
#include <locale>
#include <list>
#include <thread>
#include <typeinfo> // could possibly forward declare?
#include <limits>
#include <map>
#include <mutex>
#include <set>
#include <string>
#include <sstream>
#include <unordered_set>
#include <queue>
#include <vector>

#include <glib.h>    // for Properties
#include <gmodule.h> // for GlibModule

#include <boost/any.hpp>
#include <boost/filesystem.hpp>
#include <boost/function.hpp>
#include <boost/signals2.hpp>
#include <boost/lockfree/queue.hpp>
#include <boost/lockfree/stack.hpp>

#include "fmt/format.h"

#include "moodycamel/concurrentqueue.h"

#endif // MOJO_CORE_COMMON_HEADER_H
