#ifndef MOJO_AUDIO_FILE_TYPEDEFS_H
#define MOJO_AUDIO_FILE_TYPEDEFS_H

M_DEFINE_ALL_TYPEDEFS(AudioFile)
M_DEFINE_ALL_TYPEDEFS(AudioFileFormat)
M_DEFINE_ALL_TYPEDEFS(AudioFileModule)

#endif // MOJO_AUDIO_FILE_TYPEDEFS_H
