#! /usr/bin/env python
# encoding: utf-8
# Tim Mayberry, 2008

subdirs = '''
sndfile
'''


def init():
    pass


def configure(conf):
    print ("configure mojo-audio-file")


def build(bld):

    if bld.env.ENABLE_AMALGAMATION:
        source = 'mojo-audio-file.cpp'
        defines = 'MOJO_AMALGAMATED'
    else:
        source = bld.path.ant_glob('*.cpp',
                    excl='mojo-audio-file.cpp')
        defines = ''

    uselib = ['GMODULE-2.0', 'BOOST_FILESYSTEM', 'BOOST_SYSTEM']
    target = 'mojo-audio-file'

    if bld.env['ENABLE_SHARED']:
        bld.shlib(includes='.',
                  export_includes='.',
                  source=source,
                  uselib=uselib,
                  use=['MOJO_CORE_SHARED'],
                  defines=defines,
                  target='mojo-audio-file',
                  name='MOJO_AUDIO_FILE_SHARED')

    if bld.env['ENABLE_STATIC']:
        bld.stlib(includes='.',
                  export_includes='.',
                  source=source,
                  uselib=uselib,
                  use=['MOJO_CORE_STATIC'],
                  defines=defines,
                  target='mojo-audio-file',
                  name='MOJO_AUDIO_FILE_STATIC')

    bld.recurse(subdirs)
