#! /usr/bin/env python
# encoding: utf-8
# Tim Mayberry, 2008


def init():
    pass


def configure(conf):
    print "configure mojo-core"


def build(bld):

    if bld.env['ENABLE_AMALGAMATION']:
        if bld.env['ENABLE_SHARED']:
            bld.shlib(includes='.',
                      export_includes='.',
                      source='mojo-application.cpp',
                      uselib=[
                          'GMODULE-2.0',
                          'BOOST_FILESYSTEM',
                          'BOOST_SYSTEM'],
                      use=['GLEAM', 'MOJO_CORE_SHARED_AMALGAMATED'],
                      defines='MOJO_APPLICATION_AMALGAMATED',
                      target='mojo-application-a',
                      name='MOJO_APPLICATION_SHARED_AMALGAMATED')

        if bld.env['ENABLE_STATIC']:
            bld.stlib(includes='.',
                      export_includes='.',
                      source='mojo-application.cpp',
                      uselib=[
                          'GMODULE-2.0',
                          'BOOST_FILESYSTEM',
                          'BOOST_SYSTEM'],
                      use=['GLEAM', 'MOJO_CORE_STATIC_AMALGAMATED'],
                      defines='MOJO_APPLICATION_AMALGAMATED',
                      target='mojo-application-a',
                      name='MOJO_APPLICATION_STATIC_AMALGAMATED')

#    if ctx.env['BUILD_TESTS']:
#        ctx.recurse('tests')
