#! /usr/bin/env python
# encoding: utf-8
# Tim Mayberry, 2008

subdirs = '''
ladspa
'''


def configure(conf):
    for dir in subdirs.split():
        conf.recurse(dir)


def build(bld):
    # process subfolders from here
    bld.recurse(subdirs)
