#! /usr/bin/env python
# encoding: utf-8
# Tim Mayberry, 2008

def init():
	pass

def configure(conf):
	print "configure DummyArchive"

def build(bld):
        obj = bld.new_task_gen('cxx', 'shlib')
	obj.find_sources_in_dirs('.')
	obj.includes ='.'
#	obj.uselib = ['GMODULE-2.0', 'BOOST_FILESYSTEM', 'BOOST_SYSTEM']
	obj.uselib_local ='MOJO'
	obj.target = 'dummy_archive'
	obj.name = 'DUMMY_ARCHIVE'
