#! /usr/bin/env python
# encoding: utf-8
# Tim Mayberry, 2008


def init():
    pass


def configure(conf):
    print "configure mojo-audio-driver-jack"


def build(bld):

    if bld.env['ENABLE_SHARED']:
        bld.shlib(includes='.',
                  source=bld.path.ant_glob('*.cpp'),
                  uselib=[
                      'GMODULE-2.0',
                      'BOOST_FILESYSTEM',
                      'BOOST_SYSTEM'],
                  use=[
                      'MOJO_AUDIO_DRIVER_SHARED',
                      'MOJO_CORE_SHARED'],
                  target='mojo-audio-driver-jack',
                  name='MOJO_AUDIO_DRIVER_JACK')

    if bld.env['ENABLE_STATIC']:
        bld.stlib(includes='.',
                  source=bld.path.ant_glob('*.cpp'),
                  uselib=[
                      'GMODULE-2.0',
                      'BOOST_FILESYSTEM',
                      'BOOST_SYSTEM'],
                  use=[
                      'MOJO_AUDIO_DRIVER_STATIC',
                      'MOJO_CORE_STATIC'],
                  target='mojo-audio-driver-jack',
                  name='MOJO_AUDIO_DRIVER_JACK')
