#! /usr/bin/env python
# encoding: utf-8
# Tim Mayberry, 2008

uselibs = [
    'GTKMM-3.0',
    'GOOCANVASMM-2.0',
    'GTHREAD-2.0',
    'GMODULE-2.0',
    'BOOST_SYSTEM',
    'BOOST_FILESYSTEM'
]


def init():
    pass


def configure(conf):
    print ("configure ui")
    conf.check_cfg(
        package='gtkmm-3.0',
        atleast_version='3.8',
        args='--cflags --libs',
        mandatory=1)
    conf.check_cfg(
        package='goocanvasmm-2.0',
        atleast_version='1.9.8',
        args='--cflags --libs',
        mandatory=1)


def build(bld):
    if bld.env.ENABLE_SHARED:
        bld.program(
            source=bld.path.ant_glob('*.cpp'),
            includes='.',
            uselib=uselibs,
            use=['GLEAM_SHARED', 'MOJO_APPLICATION_SHARED', 'MOJO_CORE_SHARED'],
            target=bld.env['APPNAME'])

    if bld.env.ENABLE_STATIC:
        bld.program(
            source=bld.path.ant_glob('*.cpp'),
            includes='.',
            uselib=uselibs,
            use=['GLEAM_SHARED', 'MOJO_APPLICATION_STATIC', 'MOJO_CORE_STATIC'],
            target=bld.env['APPNAME'] + '-static')
