# vim: tabstop=4 expandtab shiftwidth=4

import tools.pkgconfig as pkgconfig

Import ('env')

rtg_test_env = env.Copy()

rtg_test_env.Append(LIBS = [ 'boost_unit_test_framework', 'rtg' ])

graph_test = rtg_test_env.Program ( 'test_graph', 'test_graph.cpp' )

Default (graph_test)
