#! /usr/bin/env python
# encoding: utf-8
# Tim Mayberry, 2008

def init():
	pass

def configure(conf):
	print "configure LADSPAAudioEffect"

def build(bld):
        obj = bld.new_task_gen('cxx', 'shlib')
	obj.find_sources_in_dirs('.')
	obj.includes ='. ../../../'
	obj.uselib = ['LADSPA']
	obj.uselib_local ='MOJO'
	obj.target = 'ladspa_audio_effect'
	obj.name = 'LADSPA_AUDIO_EFFECT'
