# vim: tabstop=4 expandtab shiftwidth=4

Import ('env')

dummy_archive_env = env.Copy()

dummy_archive_source_files = Split("""
dummy_archive.cpp
dummy_archive_plugin.cpp
""")

dummy_archive = dummy_archive_env.SharedLibrary ( 'dummy_archive', dummy_archive_source_files )

Default (dummy_archive)

if env['BUILD_TESTS']:
        test_env = env.Copy()
        test_env.Append(CXXFLAGS = '-DBOOST_TEST_DYN_LINK')
        test_env.Append(LIBS = [ 'boost_unit_test_framework', 'mojo', 'gleam', 'dummy_archive' ])
        test = test_env.Program ( 'test_dummy_archive', 'test_dummy_archive.cpp' )
        Default (test)
