#! /usr/bin/env python
# encoding: utf-8
# Tim Mayberry, 2008

def init():
	pass

def configure(conf):
	print "configure SndfileAudioFile"

def build(bld):
        obj = bld.new_task_gen('cxx', 'shlib')
	obj.find_sources_in_dirs('.')
	obj.includes ='. ../../../'
	obj.uselib = ['SNDFILE']
	obj.uselib_local ='MOJO'
	obj.target = 'sndfile_audio_file'
	obj.name = 'SNDFILE_AUDIO_FILE'
