#! /usr/bin/env python
# encoding: utf-8
# Tim Mayberry, 2008


def init():
    pass


def configure(conf):
    print ("configure mojo-archive-dummy")


def build(bld):

    if bld.env.ENABLE_AMALGAMATION:
        source = 'mojo-dummy-archive.cpp'
        defines = 'MOJO_AMALGAMATED'
    else:
        source = bld.path.ant_glob('*.cpp',
                    excl='mojo-dummy-archive.cpp')
        defines = ''

    uselib = ['GMODULE-2.0', 'BOOST_FILESYSTEM', 'BOOST_SYSTEM']
    target = 'mojo-dummy-archive'

    if bld.env['ENABLE_SHARED']:
        bld.shlib(includes='.',
                  source=source,
                  uselib=uselib,
                  use=[
                      'MOJO_ARCHIVE_SHARED',
                      'MOJO_CORE_SHARED'],
                  defines=defines,
                  target=target,
                  name='MOJO_ARCHIVE_DUMMY')

    if bld.env['ENABLE_STATIC']:
        bld.stlib(includes='.',
                  source=source,
                  uselib=uselib,
                  use=[
                      'MOJO_ARCHIVE_STATIC',
                      'MOJO_CORE_STATIC'],
                  defines=defines,
                  target=target,
                  name='MOJO_ARCHIVE_DUMMY')
