#! /usr/bin/env python
# encoding: utf-8
# Tim Mayberry, 2008


def init():
    pass


def configure(conf):
    print "configure mojo-archive-dummy"


def build(bld):

    if bld.env['ENABLE_SHARED']:
        bld.shlib(includes='.',
                  source=bld.path.ant_glob('*.cpp'),
                  uselib=[
                      'GMODULE-2.0',
                      'BOOST_FILESYSTEM',
                      'BOOST_SYSTEM'],
                  use=['GLEAM', 'MOJO_ARCHIVE_SHARED', 'MOJO_CORE_SHARED'],
                  target='mojo-archive-dummy',
                  name='MOJO_ARCHIVE_DUMMY')

    if bld.env['ENABLE_STATIC']:
        bld.stlib(includes='.',
                  source=bld.path.ant_glob('*.cpp'),
                  uselib=[
                      'GMODULE-2.0',
                      'BOOST_FILESYSTEM',
                      'BOOST_SYSTEM'],
                  use=['GLEAM', 'MOJO_ARCHIVE_STATIC', 'MOJO_CORE_STATIC'],
                  target='mojo-archive-dummy',
                  name='MOJO_ARCHIVE_DUMMY')
