#ifndef MOJO_MIDI_DRIVER_TYPEDEFS_H
#define MOJO_MIDI_DRIVER_TYPEDEFS_H

namespace mojo {

M_DEFINE_ALL_TYPEDEFS(MIDIDevice)
M_DEFINE_ALL_TYPEDEFS(MIDIInputDevice)
M_DEFINE_ALL_TYPEDEFS(MIDIOutputDevice)
M_DEFINE_ALL_TYPEDEFS(MIDIDriver)
M_DEFINE_ALL_TYPEDEFS(MIDIDriverModule)

} // namespace mojo

#endif // MOJO_MIDI_DRIVER_TYPEDEFS_H
