#! /usr/bin/env python
# encoding: utf-8
# Tim Mayberry, 2008

subdirs = '''
portmidi
winmme
'''


def init():
    pass


def configure(conf):
    print ("configure mojo-midi-driver")
    conf.recurse(subdirs)


def build(bld):

    source = 'mojo-midi-driver.cpp'
    uselib = ['GMODULE-2.0', 'BOOST_FILESYSTEM', 'BOOST_SYSTEM']
    target = 'mojo-midi-driver'

    if bld.env.ENABLE_SHARED:
        bld.shlib(includes='.',
                  export_includes='.',
                  source=source,
                  uselib=uselib,
                  use=['MOJO_CORE_SHARED'],
                  target=target,
                  name='MOJO_MIDI_DRIVER_SHARED')

    if bld.env.ENABLE_STATIC:
        bld.stlib(includes='.',
                  export_includes='.',
                  source=source,
                  uselib=uselib,
                  use=['MOJO_CORE_STATIC'],
                  target=target,
                  name='MOJO_MIDI_DRIVER_STATIC')

    bld.recurse(subdirs)
