#! /usr/bin/env python
# encoding: utf-8
# Tim Mayberry, 2008


def init():
    pass


def configure(conf):
    print "configure mojo-audio-file-sndfile"


def build(bld):

    if bld.env['ENABLE_SHARED']:
        bld.shlib(includes='.',
                  source=bld.path.ant_glob('*.cpp'),
                  uselib=[
                      'SNDFILE',
                      'GMODULE-2.0',
                      'BOOST_FILESYSTEM',
                      'BOOST_SYSTEM'],
                  use=[
                      'GLEAM_SHARED',
                      'MOJO_AUDIO_FILE_SHARED',
                      'MOJO_CORE_SHARED'],
                  target='mojo-audio-file-sndfile',
                  name='MOJO_AUDIO_FILE_SNDFILE')

    if bld.env['ENABLE_STATIC']:
        bld.stlib(includes='.',
                  source=bld.path.ant_glob('*.cpp'),
                  uselib=[
                      'SNDFILE',
                      'GMODULE-2.0',
                      'BOOST_FILESYSTEM',
                      'BOOST_SYSTEM'],
                  use=[
                      'GLEAM_STATIC',
                      'MOJO_AUDIO_FILE_STATIC',
                      'MOJO_CORE_STATIC'],
                  target='mojo-audio-file-sndfile',
                  name='MOJO_AUDIO_FILE_SNDFILE')
