# vim: tabstop=4 expandtab shiftwidth=4

import tools.pkgconfig as pkgconfig

Import ('env')

gleam_test_env = env.Clone()

gleam_test_env.Append(CXXFLAGS = '-DBOOST_TEST_DYN_LINK')
gleam_test_env.Append(LIBS = [ 'boost_unit_test_framework', 'gleam' ])

filesystem_paths_test = gleam_test_env.Program ( 'test_filesystem_paths', 'test_filesystem_paths.cpp' )

Default (filesystem_paths_test)
