#! /usr/bin/env python
# encoding: utf-8
# Tim Mayberry, 2008

tests='''
test_filesystem_paths
'''.split()

def build(bld):
	for test in tests:
		obj = bld.new_task_gen('cxx', 'program')
		obj.source = test + '.cpp'
		obj.includes ='. ../..'
		obj.uselib = 'BOOST_UNIT_TEST_FRAMEWORK'
		obj.uselib_local ='GLEAM'
		obj.target = test
