# -*- python -*-
#
# vim: tabstop=4 expandtab shiftwidth=4 softtabstop=4 

import os

dirs = [
    'cformat',
    'gleam',
    'mojo',
    'plugins',
    'ui',
    'mojo-gtk'
    ]

for dir in dirs:
        SConscript( os.path.join( dir, 'SConscript' ) )
