#! /usr/bin/env python
# encoding: utf-8
# Tim Mayberry, 2008

subdirs='''
gleam
mojo
ui
modules
'''

def configure(conf):
	for dir in subdirs.split():
		conf.sub_config(dir)

def build(bld):
	# process subfolders from here
	bld.add_subdirs(subdirs)
