# vim: tabstop=4 expandtab shiftwidth=4

import tools.pkgconfig as pkgconfig

Import ('env')

mojo_gtkmm_deps = \
{
    'gtkmm-2.4'             : '2.12.1',
    'goocanvasmm-1.0'       : '0.4'
}

mojo_gtkmm_env = env.Clone()

mojo_gtkmm_env.Append(LIBS = ['gleam', 'mojo'])

pkgconfig.ParseDependencies ( mojo_gtkmm_env, mojo_gtkmm_deps )

mojo_gtkmm_source_files = Split("""
app.cpp
audio_track_view_item.cpp
audio_track_list_item.cpp
audio_track_canvas_item.cpp
bus.cpp
dispatcher.cpp
main.cpp
preferences_dialog.cpp
project_objects.cpp
project_setup_dialog.cpp
project_window.cpp
timers.cpp
track_canvas.cpp
track_canvas_item.cpp
track_list.cpp
track_list_item.cpp
track_view_factory.cpp
track_view.cpp
track_view_item.cpp
track_view_item_factory.cpp
transport_toolbar.cpp
utils.cpp
""")

all_source_files = \
mojo_gtkmm_source_files

mojo_gtkmm = mojo_gtkmm_env.Program( env['VERSIONED_NAME'], all_source_files)

Default(mojo_gtkmm)

env.Install(env['BINDIR'], mojo_gtkmm)
