#! /usr/bin/env python
# encoding: utf-8
# Tim Mayberry, 2008

def init():
	pass

def configure(conf):
	print "configure mojo-gtkmm"

def build(bld):
	obj = bld.create_obj('cpp', 'program')
	obj.find_sources_in_dirs('.')
	obj.includes ='..'
	obj.uselib ='GTKMM GOOCANVASMM'
	obj.uselib_local ='GLEAM'
	obj.target = 'mojo-gtkmm'
	#obj.name = 'MOJO-GTKMM'
