#! /usr/bin/env python
# encoding: utf-8
# Tim Mayberry, 2008

def init():
	pass

def configure(conf):
	print "configure mojo-gtkmm"

def build(ctx):
	mojo_program = ctx(
		features = "cxx cxxprogram",
		source = ctx.path.ant_glob('*.cpp'),
		includes ='..',
		uselib = 'GTKMM-3.0 GOOCANVASMM-2.0 GTHREAD-2.0',
		use = 'GLEAM MOJO',
		target = ctx.env['APPNAME'])
		#name = 'MOJO-GTKMM'
