# -*- python -*-
# vim: tabstop=4 expandtab shiftwidth=4

import tools.pkgconfig as pkgconfig

Import ('env')

mojo_test_env = env.Copy()
mojo_test_env.Append(CXXFLAGS = '-DBOOST_TEST_DYN_LINK')
mojo_test_env.Append(LIBS = [ 'boost_unit_test_framework', 'mojo', 'gleam' ])

sequence_test = mojo_test_env.Program ( 'test_sequence', 'test_sequence.cpp' )

Default (sequence_test)

type_system_test = mojo_test_env.Program ( 'test_type_system', 'test_type_system.cpp' )

Default (type_system_test)

graph_test = mojo_test_env.Program ( 'test_graph', 'test_graph.cpp' )

Default (graph_test)

plugin_utils_test = mojo_test_env.Program ( 'test_plugin_utils', 'test_plugin_utils.cpp' )

Default (plugin_utils_test)

project_test = mojo_test_env.Program ( 'test_project', 'test_project.cpp' )

Default (project_test)

app_test = mojo_test_env.Program ( 'test_application', 'test_application.cpp' )

Default (app_test)
