# -*- python -*-
# vim: tabstop=4 expandtab shiftwidth=4

import tools.pkgconfig as pkgconfig

Import ('env')

test_deps = \
{
    'glib-2.0'      : '2.10.1'
#    'gmodule-2.0'   : '2.10.1'
#    'gthread-2.0'   : '2.10.1',
#    'glibmm-2.4'    : '2.8.1'
}

mojo_test_env = env.Clone()
mojo_test_env.Append(CXXFLAGS = '-DBOOST_TEST_DYN_LINK')
mojo_test_env.Append(LIBS = [ 'boost_unit_test_framework', 'mojo', 'gleam' ])

pkgconfig.ParseDependencies ( mojo_test_env, test_deps )

tests='''
test_sequence
test_type_system
test_graph
test_plugin_utils
test_project
test_audition
test_app
test_archive
test_audio_clip
test_audio_effect
test_filesystem_paths
test_project_directory
test_audiofile_plugins
test_file_utils
test_audio_driver_plugins
'''.split()

for test in tests:
        test_program = mojo_test_env.Program ( test, test+'.cpp' )
        Default (test_program)
